version: "3.9"
services:
    postgresql:
            image: postgres
            environment:
                - POSTGRES_PASSWORD=password
            ports:
                - 65432:5432
    mariadb:
            image: mariadb
            environment:
                - MARIADB_ROOT_PASSWORD=password
    mysql:
            image: mysql
            environment:
                - MYSQL_ROOT_PASSWORD=password