// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotGrocy;

namespace NotGrocy.MysqlMigrations.Migrations
{
    [DbContext(typeof(NotGrocyContext))]
    [Migration("20210729211215_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("NotGrocy.Models.ApiKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey1")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("api_key");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires");

                    b.Property<string>("KeyType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasColumnName("key_type")
                        .HasDefaultValueSql("'default'");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_used");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey1")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("api_keys");
                });

            modelBuilder.Entity("NotGrocy.Models.Battery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("active")
                        .HasDefaultValueSql("1");

                    b.Property<long>("ChargeIntervalDays")
                        .HasColumnType("bigint")
                        .HasColumnName("charge_interval_days");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<string>("UsedIn")
                        .HasColumnType("longtext")
                        .HasColumnName("used_in");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex(new[] { "Id", "Active" }, "ix_batteries_performance1");

                    b.ToTable("batteries");
                });

            modelBuilder.Entity("NotGrocy.Models.BatteryChargeCycle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("BatteryId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("battery_id");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<DateTime>("TrackedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tracked_time");

                    b.Property<long>("Undone")
                        .HasColumnType("bigint")
                        .HasColumnName("undone");

                    b.Property<DateTime>("UndoneTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("undone_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("battery_charge_cycles");
                });

            modelBuilder.Entity("NotGrocy.Models.Chore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("active")
                        .HasDefaultValueSql("1");

                    b.Property<string>("AssignmentConfig")
                        .HasColumnType("longtext")
                        .HasColumnName("assignment_config");

                    b.Property<string>("AssignmentType")
                        .HasColumnType("longtext")
                        .HasColumnName("assignment_type");

                    b.Property<long>("ConsumeProductOnExecution")
                        .HasColumnType("bigint")
                        .HasColumnName("consume_product_on_execution");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<long?>("NextExecutionAssignedToUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("next_execution_assigned_to_user_id");

                    b.Property<string>("PeriodConfig")
                        .HasColumnType("longtext")
                        .HasColumnName("period_config");

                    b.Property<long?>("PeriodDays")
                        .HasColumnType("bigint")
                        .HasColumnName("period_days");

                    b.Property<long>("PeriodInterval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("period_interval")
                        .HasDefaultValueSql("1");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("period_type");

                    b.Property<double?>("ProductAmount")
                        .HasColumnType("double")
                        .HasColumnName("product_amount");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long?>("Rollover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rollover")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<long?>("TrackDateOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("track_date_only")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex(new[] { "Id", "Active" }, "ix_chores_performance1");

                    b.ToTable("chores");
                });

            modelBuilder.Entity("NotGrocy.Models.ChoresLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ChoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("chore_id");

                    b.Property<long?>("DoneByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("done_by_user_id");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<DateTime>("TrackedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tracked_time");

                    b.Property<long>("Undone")
                        .HasColumnType("bigint")
                        .HasColumnName("undone");

                    b.Property<DateTime>("UndoneTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("undone_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("chores_log");
                });

            modelBuilder.Entity("NotGrocy.Models.Equipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("InstructionManualFileName")
                        .HasColumnType("longtext")
                        .HasColumnName("instruction_manual_file_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("equipment");
                });

            modelBuilder.Entity("NotGrocy.Models.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<long>("IsFreezer")
                        .HasColumnType("bigint")
                        .HasColumnName("is_freezer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("locations");
                });

            modelBuilder.Entity("NotGrocy.Models.MealPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("Day")
                        .HasColumnType("DATE")
                        .HasColumnName("day");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<double?>("ProductAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasColumnName("product_amount")
                        .HasDefaultValueSql("0");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long?>("ProductQuId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_qu_id");

                    b.Property<long?>("RecipeId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipe_id");

                    b.Property<long?>("RecipeServings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("recipe_servings")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<string>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasColumnName("type")
                        .HasDefaultValueSql("'recipe'");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("meal_plan");
                });

            modelBuilder.Entity("NotGrocy.Models.PermissionHierarchy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<long?>("Parent")
                        .HasColumnType("bigint")
                        .HasColumnName("parent");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permission_hierarchy");
                });

            modelBuilder.Entity("NotGrocy.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("This is a test");

                    b.Property<long?>("Calories")
                        .HasColumnType("bigint")
                        .HasColumnName("calories");

                    b.Property<long>("DefaultBestBeforeDays")
                        .HasColumnType("bigint")
                        .HasColumnName("default_best_before_days");

                    b.Property<long>("DefaultBestBeforeDaysAfterFreezing")
                        .HasColumnType("bigint")
                        .HasColumnName("default_best_before_days_after_freezing");

                    b.Property<long>("DefaultBestBeforeDaysAfterOpen")
                        .HasColumnType("bigint")
                        .HasColumnName("default_best_before_days_after_open");

                    b.Property<long>("DefaultBestBeforeDaysAfterThawing")
                        .HasColumnType("bigint")
                        .HasColumnName("default_best_before_days_after_thawing");

                    b.Property<long>("DefaultPrintStockLabel")
                        .HasColumnType("bigint")
                        .HasColumnName("default_print_stock_label");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<long>("DueType")
                        .HasColumnType("bigint")
                        .HasColumnName("due_type");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("location_id");

                    b.Property<long>("MinStockAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("min_stock_amount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<long>("ParentProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_product_id");

                    b.Property<string>("PictureFileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("picture_file_name");

                    b.Property<long?>("ProductGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_group_id");

                    b.Property<double>("QuFactorPurchaseToStock")
                        .HasColumnType("double")
                        .HasColumnName("qu_factor_purchase_to_stock");

                    b.Property<long>("QuIdPurchase")
                        .HasColumnType("bigint")
                        .HasColumnName("qu_id_purchase");

                    b.Property<long>("QuIdStock")
                        .HasColumnType("bigint")
                        .HasColumnName("qu_id_stock");

                    b.Property<double>("QuickConsumeAmount")
                        .HasColumnType("double")
                        .HasColumnName("quick_consume_amount");

                    b.Property<DateTime?>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<long?>("ShoppingLocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("shopping_location_id");

                    b.Property<double>("TareWeight")
                        .HasColumnType("double")
                        .HasColumnName("tare_weight");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("products");
                });

            modelBuilder.Entity("NotGrocy.Models.ProductBarcode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<double?>("Amount")
                        .HasColumnType("double")
                        .HasColumnName("amount");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("barcode");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("last_price");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long?>("QuId")
                        .HasColumnType("bigint")
                        .HasColumnName("qu_id");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<long?>("ShoppingLocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("shopping_location_id");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex(new[] { "Barcode" }, "ix_product_barcodes")
                        .IsUnique();

                    b.ToTable("product_barcodes");
                });

            modelBuilder.Entity("NotGrocy.Models.ProductGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("product_groups");
                });

            modelBuilder.Entity("NotGrocy.Models.QuantityUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NamePlural")
                        .HasColumnType("longtext")
                        .HasColumnName("name_plural");

                    b.Property<string>("PluralForms")
                        .HasColumnType("longtext")
                        .HasColumnName("plural_forms");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("quantity_units");
                });

            modelBuilder.Entity("NotGrocy.Models.QuantityUnitConversion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<double>("Factor")
                        .HasColumnType("double")
                        .HasColumnName("factor");

                    b.Property<long>("FromQuId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_qu_id");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<long>("ToQuId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_qu_id");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("quantity_unit_conversions");
                });

            modelBuilder.Entity("NotGrocy.Models.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("BaseServings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("base_servings")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<long?>("DesiredServings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("desired_servings")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<long>("NotCheckShoppinglist")
                        .HasColumnType("bigint")
                        .HasColumnName("not_check_shoppinglist");

                    b.Property<string>("PictureFileName")
                        .HasColumnType("longtext")
                        .HasColumnName("picture_file_name");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<string>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("type")
                        .HasDefaultValueSql("'normal'");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex(new[] { "Name", "Type" }, "ix_recipes");

                    b.ToTable("recipes");
                });

            modelBuilder.Entity("NotGrocy.Models.RecipesNesting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("IncludesRecipeId")
                        .HasColumnType("bigint")
                        .HasColumnName("includes_recipe_id");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipe_id");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<long?>("Servings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("servings")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RecipeId", "IncludesRecipeId")
                        .IsUnique();

                    b.ToTable("recipes_nestings");
                });

            modelBuilder.Entity("NotGrocy.Models.RecipesPo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<double>("Amount")
                        .HasColumnType("double")
                        .HasColumnName("amount");

                    b.Property<string>("IngredientGroup")
                        .HasColumnType("longtext")
                        .HasColumnName("ingredient_group");

                    b.Property<long>("NotCheckStockFulfillment")
                        .HasColumnType("bigint")
                        .HasColumnName("not_check_stock_fulfillment");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<long>("OnlyCheckSingleUnitInStock")
                        .HasColumnType("bigint")
                        .HasColumnName("only_check_single_unit_in_stock");

                    b.Property<double>("PriceFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasColumnName("price_factor")
                        .HasDefaultValueSql("1");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long?>("QuId")
                        .HasColumnType("bigint")
                        .HasColumnName("qu_id");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipe_id");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<string>("VariableAmount")
                        .HasColumnType("longtext")
                        .HasColumnName("variable_amount");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("recipes_pos");
                });

            modelBuilder.Entity("NotGrocy.Models.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_used");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("session_key");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SessionKey")
                        .IsUnique();

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("NotGrocy.Models.ShoppingList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("amount")
                        .HasDefaultValueSql("0");

                    b.Property<long?>("Done")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("done")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long?>("QuId")
                        .HasColumnType("bigint")
                        .HasColumnName("qu_id");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<long?>("ShoppingListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("shopping_list_id")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("shopping_list");
                });

            modelBuilder.Entity("NotGrocy.Models.ShoppingList1", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("shopping_lists");
                });

            modelBuilder.Entity("NotGrocy.Models.ShoppingLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("shopping_locations");
                });

            modelBuilder.Entity("NotGrocy.Models.Stock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("BestBeforeDate")
                        .HasColumnType("DATE")
                        .HasColumnName("best_before_date");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("location_id");

                    b.Property<long>("Open")
                        .HasColumnType("bigint")
                        .HasColumnName("open");

                    b.Property<DateTime>("OpenedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("opened_date");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("price");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("PurchasedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("purchased_date");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<long?>("ShoppingLocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("shopping_location_id");

                    b.Property<string>("StockId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("stock_id");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex(new[] { "ProductId", "Open", "BestBeforeDate", "Amount" }, "ix_stock_performance1");

                    b.ToTable("stock");
                });

            modelBuilder.Entity("NotGrocy.Models.StockLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("BestBeforeDate")
                        .HasColumnType("DATE")
                        .HasColumnName("best_before_date");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("longtext")
                        .HasColumnName("correlation_id");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("location_id");

                    b.Property<DateTime>("OpenedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("opened_date");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("price");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("PurchasedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("purchased_date");

                    b.Property<long?>("RecipeId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipe_id");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<long?>("ShoppingLocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("shopping_location_id");

                    b.Property<long>("Spoiled")
                        .HasColumnType("bigint")
                        .HasColumnName("spoiled");

                    b.Property<string>("StockId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("stock_id");

                    b.Property<long?>("StockRowId")
                        .HasColumnType("bigint")
                        .HasColumnName("stock_row_id");

                    b.Property<string>("TransactionId")
                        .HasColumnType("longtext")
                        .HasColumnName("transaction_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("transaction_type");

                    b.Property<long>("Undone")
                        .HasColumnType("bigint")
                        .HasColumnName("undone");

                    b.Property<DateTime>("UndoneTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("undone_timestamp");

                    b.Property<DateTime>("UsedDate")
                        .HasColumnType("DATE")
                        .HasColumnName("used_date");

                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("stock_log");
                });

            modelBuilder.Entity("NotGrocy.Models.Task", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("AssignedToUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<long>("Done")
                        .HasColumnType("bigint")
                        .HasColumnName("done");

                    b.Property<DateTime>("DoneTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("done_timestamp");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("NotGrocy.Models.TaskCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("task_categories");
                });

            modelBuilder.Entity("NotGrocy.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("PictureFileName")
                        .HasColumnType("longtext")
                        .HasColumnName("picture_file_name");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("NotGrocy.Models.UserPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("permission_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId", "PermissionId")
                        .IsUnique();

                    b.ToTable("user_permissions");
                });

            modelBuilder.Entity("NotGrocy.Models.UserSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("key");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<DateTime>("RowUpdatedTimestamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_updated_timestamp");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId", "Key")
                        .IsUnique();

                    b.ToTable("user_settings");
                });

            modelBuilder.Entity("NotGrocy.Models.Userentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("caption");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("IconCssClass")
                        .HasColumnType("longtext")
                        .HasColumnName("icon_css_class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<long>("ShowInSidebarMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("show_in_sidebar_menu")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("userentities");
                });

            modelBuilder.Entity("NotGrocy.Models.Userfield", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("caption");

                    b.Property<string>("Config")
                        .HasColumnType("longtext")
                        .HasColumnName("config");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("entity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<long>("ShowAsColumnInTables")
                        .HasColumnType("bigint")
                        .HasColumnName("show_as_column_in_tables");

                    b.Property<long?>("SortNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sort_number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Entity", "Name")
                        .IsUnique();

                    b.ToTable("userfields");
                });

            modelBuilder.Entity("NotGrocy.Models.UserfieldValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("FieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("field_id");

                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("FieldId", "ObjectId")
                        .IsUnique();

                    b.ToTable("userfield_values");
                });

            modelBuilder.Entity("NotGrocy.Models.Userobject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("RowCreatedTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("row_created_timestamp");

                    b.Property<long>("UserentityId")
                        .HasColumnType("bigint")
                        .HasColumnName("userentity_id");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("userobjects");
                });
#pragma warning restore 612, 618
        }
    }
}
